# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run plgd/hub tests with cloud_server

on:
  push:

env:
  TEST_CLOUD_SERVER_IMAGE: ghcr.io/plgd-dev/hub/test-cloud-server:latest

jobs:
  plgd-hub-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: cloud-server-debug
            file: docker/apps/Dockerfile.cloud-server-debug
            tag: cloud-server-debug:debug
          - name: cloud-server-discovery-resource-observable-debug
            file: docker/apps/Dockerfile.cloud-server-discovery-resource-observable-debug
            tag: cloud-server-discovery-resource-observable-debug:debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Build cloud server docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ${{ matrix.file }}
          tags: ${{ matrix.tag }}
      
      - name: Pull plgd hub tests image
        run: docker pull ${{ env.TEST_CLOUD_SERVER_IMAGE }}

      - name: Run cloud server container
        run: docker run --privileged -d --network=host -v `pwd`/data:/tmp --name ${{ matrix.name }} ${{ matrix.tag }} devsim-`hostname`

      - name: Run plgd hub tests image
        run: docker run --rm --network=host ${{ env.TEST_CLOUD_SERVER_IMAGE }}

      - name: Collect cloud server logs when the test fails
        if: ${{ failure() }}
        run: cat `pwd`/data/0.log

      - name: Remove cloud server container
        run: docker rm -f ${{ matrix.name }}
      

