# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Run plgd/device tests with cloud_server

on:
  push:

env:
  TEST_CLOUD_SERVER_IMAGE: ghcr.io/plgd-dev/device/test-cloud-server:vnext
  CERT_TOOL_IMAGE: ghcr.io/plgd-dev/hub/cert-tool:vnext
  CERT_PATH: .tmp/pki_certs

jobs:
  plgd-device-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: cloud-server-debug
            file: docker/apps/Dockerfile.cloud-server-debug
            tag: cloud-server-debug:debug
          - name: cloud-server-discovery-resource-observable-debug
            file: docker/apps/Dockerfile.cloud-server-discovery-resource-observable-debug
            tag: cloud-server-discovery-resource-observable-debug:debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
     
      - name: Build cloud server docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: ${{ matrix.file }}
          tags: ${{ matrix.tag }}
      
      - name: Pull plgd device tests image
        run: docker pull ${{ env.TEST_CLOUD_SERVER_IMAGE }}

      - name: Setup environment
        run: |
          mkdir -p `pwd`/${{ env.CERT_PATH }}
          docker pull ${{ env.CERT_TOOL_IMAGE }}
          docker run --rm -v `pwd`/${{ env.CERT_PATH }}:/out ${{ env.CERT_TOOL_IMAGE }} --outCert=/out/cloudca.pem --outKey=/out/cloudcakey.pem --cert.subject.cn="ca" --cmd.generateRootCA
          docker run --rm -v `pwd`/${{ env.CERT_PATH }}:/out ${{ env.CERT_TOOL_IMAGE }} --signerCert=/out/cloudca.pem --signerKey=/out/cloudcakey.pem  --outCert=/out/intermediatecacrt.pem --outKey=/out/intermediatecakey.pem --cert.basicConstraints.maxPathLen=0 --cert.subject.cn="intermediateCA" --cmd.generateIntermediateCA
          docker run --rm -v `pwd`/${{ env.CERT_PATH }}:/out ${{ env.CERT_TOOL_IMAGE }} --signerCert=/out/intermediatecacrt.pem --signerKey=/out/intermediatecakey.pem --outCert=/out/mfgcrt.pem --outKey=/out/mfgkey.pem --cert.san.domain=localhost --cert.san.ip=127.0.0.1 --cert.subject.cn="mfg" --cmd.generateCertificate
          sudo chmod -R 0777 ${{ env.CERT_PATH }}

      - name: Run cloud server container
        run: docker run --privileged -d --network=host -v `pwd`/${{ env.CERT_PATH }}:/pki_certs -v `pwd`/data:/tmp --name ${{ matrix.name }} ${{ matrix.tag }} devsim-`hostname`

      - name: Run plgd device tests image
        run: docker run --rm --network=host -v `pwd`/${{ env.CERT_PATH }}:/pki_certs ${{ env.TEST_CLOUD_SERVER_IMAGE }} -test.parallel 1 -test.v

      - name: Collect cloud server logs when the test fails
        if: ${{ failure() }}
        run: cat `pwd`/data/0.log

      - name: Remove cloud server container
        run: docker rm -f ${{ matrix.name }}
      

